### ISSUE TITLE
Register ICommandProcessor in .net core DI

### ISSUE THREAD

**Issue by TNMephaGroup** [hlaueriksson/CommandQuery#3]
I am having an issue to register ICommandProcessor in WorkerProcess .net core DI

stack trace:
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: CommandQuery.ICommandProcessor Lifetime: Transient ImplementationType: CommandQuery.CommandProcessor': Unable to resolve service for type 'CommandQuery.ICommandTypeCollection' while attempting to activate 'CommandQuery.CommandProcessor'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: CommandQuery.ICommandProcessor Lifetime: Transient ImplementationType: CommandQuery.CommandProcessor': Unable to resolve service for type 'CommandQuery.ICommandTypeCollection' while attempting to activate 'CommandQuery.CommandProcessor'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'CommandQuery.ICommandTypeCollection' while attempting to activate 'CommandQuery.CommandProcessor'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at WorkerWithCommandProcessor.Program.Main(String[] args) in C:\Users\atran1\source\repos\WorkerWithCommandProcessor\WorkerWithCommandProcessor\Program.cs:line 15

How to reproduce:
fetch repo https://github.com/TNMephaGroup/WorkerWithCommandProcessor
run the solution

**Comment by hlaueriksson** [comment]
You can do something like this:

```
using CommandQuery.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WorkerService1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                    services.AddCommands(typeof(Program).Assembly);
                });
    }
}
```

The `AddCommands` extension method will register `ICommandProcessor` and `ICommandTypeCollection`, along with your own command handlers in the given assembly.

The `CommandQuery.DependencyInjection.dll` is included in the `CommandQuery.AspNetCore` package.

In the next release of CommandQuery, I will publish `CommandQuery.DependencyInjection` as a separate package. Then you don't need to depend on the MVC stuff from `CommandQuery.AspNetCore`.

**Comment by TNMephaGroup** [comment]
awesome! keep up with your work!

**Comment by hlaueriksson** [comment]
`CommandQuery.DependencyInjection` is now available as a separate package;
https://www.nuget.org/packages/CommandQuery.DependencyInjection/
